class Location {
  int xpos;  //x-coordinate
  int ypos;  //y-coordinate
  Tile tile;
  Location (int x, int y, Tile t) {
    xpos = x;
    ypos = y;
    tile = t;
  }
    
  int getX() {
    /*Returns x-coordinate */
    return xpos;
  }
      
  int getY() {
    /*Returns y-coordinate */
    return ypos;
  }
    
  float distFrom(Location other) {
    /*Returns distance of self from other location */
    int ox = other.getX();
    int oy = other.getY();
    int xDist = xpos - ox;
    int yDist = ypos - oy;
    float dist = sqrt(sq(xDist) + sq(yDist));
    return dist;
  }
  
  void changeTile(Tile t) {
    /* Changes Tile of the Location to t */
    tile = t;
  }
  
  void changeLandUse(LandUse lu) {
    /* Changes the LandUse of the Tile at this Location to lu */
    tile.changeLandType(lu);
  }
  
  int getPollution() {
  /*Returns pollution generated by tile at the Location */
  return tile.getPollution();
  }
    
  @Override
  public String toString() {
    return "<" + str(xpos) + ", " + str(ypos)+ ">";
  }
}